# Tomcat Configuration
server.port: 8080
server.contextPath: /pardoschicken

# Datasource Configuration
spring.datasource.driver: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://<ip>/<database>
spring.datasource.username: user
spring.datasource.password: password

# Hibernate Configuration
hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
hibernate.showSql: true
hibernate.releaseMode: after_transaction
hibernate.useUnicode: true
hibernate.charSet: UTF8
hibernate.packagesToScan: pe.pardoschicken.reserva