# Tomcat Configuration
server.port: 8080
server.contextPath: /pardoschicken

# Datasource Configuration
spring.datasource.driver: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://<ip>/<database>
spring.datasource.username: user
spring.datasource.password: password

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.connection.release_mode: after_transaction
spring.jpa.properties.hibernate.connection.useUnicode: true
spring.jpa.properties.hibernate.connection.charSet: UTF8