# Tomcat Configuration
server.port: 8080
server.contextPath: /pardoschicken
frontend.server: localhost
frontend.port: 4200

# Datasource Configuration
spring.datasource.driver: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://jcuica.ctenzgkydnvm.us-east-1.rds.amazonaws.com:3306/atencioncliente?useSSL=false
spring.datasource.username: jcuica
spring.datasource.password: 931534817Cui..